import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiNodedotjs,
  SiMongodb,
  SiExpress,
  SiTailwindcss,
  SiPostgresql,
  SiPrisma,
  SiGit,
  SiDocker,
  SiPython,
  SiJavascript,
  SiRedis,
  SiPostman,
  SiSocketdotio,
  SiGithubactions,
  SiGoogle,
  SiOpenai,
  SiReactquery,
  SiShadcnui,
  SiFramer,
  SiClerk,
  SiRabbitmq,
  SiCloudinary,
  SiJsonwebtokens,
} from "react-icons/si";

export const getTechDetails = (tag) => {
  const normalizedTag = tag.toLowerCase().replace(/[\s\.]/g, "");
  const techMap = {
    react: { icon: SiReact, color: "text-blue-500", name: "React" },
    nextjs: { icon: SiNextdotjs, color: "text-white", name: "Next.js" },
    nextjs15: { icon: SiNextdotjs, color: "text-white", name: "Next.js 15" },
    typescript: { icon: SiTypescript, color: "text-blue-600", name: "TypeScript" },
    node: { icon: SiNodedotjs, color: "text-green-500", name: "Node.js" },
    nodejs: { icon: SiNodedotjs, color: "text-green-500", name: "Node.js" },
    mongodb: { icon: SiMongodb, color: "text-green-600", name: "MongoDB" },
    express: { icon: SiExpress, color: "text-white", name: "Express.js" },
    expressjs: { icon: SiExpress, color: "text-white", name: "Express.js" },
    tailwind: { icon: SiTailwindcss, color: "text-cyan-400", name: "Tailwind CSS" },
    tailwindcss: { icon: SiTailwindcss, color: "text-cyan-400", name: "Tailwind CSS" },
    postgresql: { icon: SiPostgresql, color: "text-blue-400", name: "PostgreSQL" },
    prisma: { icon: SiPrisma, color: "text-white", name: "Prisma" },
    git: { icon: SiGit, color: "text-orange-500", name: "Git" },
    docker: { icon: SiDocker, color: "text-blue-500", name: "Docker" },
    python: { icon: SiPython, color: "text-yellow-400", name: "Python" },
    javascript: { icon: SiJavascript, color: "text-yellow-400", name: "JavaScript" },
    redis: { icon: SiRedis, color: "text-red-500", name: "Redis" },
    socket: { icon: SiSocketdotio, color: "text-white", name: "Socket.io" },
    socketio: { icon: SiSocketdotio, color: "text-white", name: "Socket.io" },
    geminiai: { icon: SiGoogle, color: "text-blue-400", name: "Gemini AI" },
    langchain: { image: "/logos/langchain-color.svg", name: "LangChain" },
    resend: { icon: SiJavascript, color: "text-white", name: "Resend" },
    webrtc: { image: "/logos/webrtc-svgrepo-com.svg", name: "WebRTC" },
    reactquery: { icon: SiReactquery, color: "text-red-400", name: "React Query" },
    shadcnui: { icon: SiShadcnui, color: "text-white", name: "Shadcn UI" },
    framermotion: { icon: SiFramer, color: "text-purple-500", name: "Framer Motion" },
    clerk: { image: "/logos/idC1jR8p-G_logos.jpeg", name: "Clerk" },
    graphql: { icon: SiJavascript, color: "text-pink-500", name: "GraphQL" },
    rabbitmq: { icon: SiRabbitmq, color: "text-orange-600", name: "RabbitMQ" },
    microservices: { icon: SiDocker, color: "text-blue-400", name: "Microservices" },
    cloudinary: { icon: SiCloudinary, color: "text-blue-400", name: "Cloudinary" },
    jwt: { icon: SiJsonwebtokens, color: "text-pink-500", name: "JWT" },
    multer: { icon: SiNodedotjs, color: "text-green-500", name: "Multer" },
  };

  return techMap[normalizedTag] || { icon: null, color: "text-gray-400", name: tag };
};
